#服务器端口
server:
  port: 8001
#mysql连接
spring:
  datasource:
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 1579257489@qq.com
    password: aseeauffwtnwhajg
    default-encoding: UTF-8 #默认编码格式
    properties:
        mail:
          debug: true #启动debug调试
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
  redis:
    host: localhost
    port: 6379
    password: 123456
  session:
    timeout: 30m
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session


# mybatis
mybatis-plus:
  #实体映射文件位置
  mapper-locations: classpath:/mapper/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto
  #别名设置，实体类名作为别名
  type-aliases-package: com.zyw.demo_boot.pojo
  #控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl